# The following will most likely change from year to year
dates:
  month: September
  start: 9
  end: 12
  year: 2021
registration_window:
  open: 2021-07-14
  close: 2021-09-01
fees:
  registration:
    adult: 50
    child: 0

# The following should rarely change
front_page_message:
  pre_registration: Stay tuned.
  during_registration:
  closed_registration: Online registration is now closed, but the Rendezvous is ON!
  post_rendezvous: See you next year!
info_pages:
  - faq
  - history
  - legal_information
  - vendors
suggested_donations:
    - 10
    - 25
    - 50
    - 100
payment_methods:
  - credit card
  - check
  - cash
registration_statuses:
  - initiated
  - in review
  - payment due
  - complete
  - updated
  - updating
  - cancelled
transaction_types:
  - payment
  - refund
official_contact:
  mailing_address_array:
    - "Citroen Rendezvous, LLC"
    - "245 Harvester Road"
    - "Orange, CT 06477-2929"
    - "United States"
  chief_officer: David Cossitt Levy
  email: david.cossitt.levy@gmail.com
vehicle_marques:
  - Citroen
  - Panhard
  - Peugeot
  - Renault
  - Other
vehicle_models:
  - C2
  - Traction Avant (11)
  - Traction Avant (15)
  - 2CV (sedan)
  - 2CV (truckette)
  - Dyane
  - D (early)
  - D (late)
  - D (wagon)
  - D (Chapron)
  - SM
  - CX (series 1)
  - CX (series 2)
  - CXA
  - GS
  - GSA
  - Ami
  - Dyane
  - Mehari
  - Visa
  - XM
  - Xantia
  - C6
  - 'H-Van'
judging_categories:
  - 'C2 / Traction Avant'
  - 'ID / DS'
  - '2CV / Truckette'
  - 'SM'
  - 'CX / CXA'
  - 'Ami / Dyane / Mehari / Visa'
  - 'GS / GSA / XM / Xantia / C6 / H-Van'
  - 'Other French'
  - 'Non-French'
countries:
  USA: United States
  CAN: Canada
  MEX: Mexico
  AUT: Austria
  BEL: Belgium
  HRV: Croatia
  DNK: Denmark
  FRA: France
  DEU: Germany
  IRL: Ireland
  ITA: Italy
  NLD: Netherlands
  NOR: Norway
  PRT: Portugal
  ESP: Spain
  SWE: Sweden
  CHE: Switzerland
  GBR: United Kingdom

provinces:
  - AB
  - BC
  - MB
  - NB
  - NF
  - NT
  - NS
  - 'ON'
  - PE
  - QC
  - SK
  - YT

print_token: "bLsa1e0Kq04hinHnX7ENvE2X389rhrLy"
mailchimp:
  api_key: <%= ENV['RENDEZVOUS_MAILCHIMP_API_KEY'] %>
  list:
    name: Citroen Rendezvous
    list_id: 9e696fe93f

development:
  facebook:
    app_id: <%= ENV['RENDEZVOUS_FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['RENDEZVOUS_FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_SECRET'] %>
  mailer:
    delivery_method: :smtp
    settings:
      :address:             smtp.gmail.com
      :domain:              localhost
      :port:                587
      :user_name:           <%= ENV['GMAIL_USER'] %>
      :password:            <%= ENV['GMAIL_PASS'] %>
      :authentication:      :plain
      :enable_starttls_auto: true

  inquiry_recipients:
    - tim@wordsareimages.com

staging:
  facebook:
    app_id: <%= ENV['RENDEZVOUS_FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['RENDEZVOUS_FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_SECRET'] %>
  mailer:
    delivery_method: :smtp
    settings:
      address:               email-smtp.us-east-1.amazonaws.com
      domain:                rendezvous.wordsareimages.com
      port:                  587
      user_name:             <%= ENV['RENDEZVOUS_SES_USER'] %>
      password:              <%= ENV['RENDEZVOUS_SES_PASSWORD'] %>
      authentication:        :login
      enable_starttls_auto:  true

  inquiry_recipients:
    - hellman.michaela@gmail.com
    - david.cossitt.levy@gmail.com
    - toaph@yahoo.com
    - tim@wordsareimages.com

production:
  facebook:
    app_id: <%= ENV['RENDEZVOUS_FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['RENDEZVOUS_FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_SECRET'] %>

  mailer:
    delivery_method: :smtp
    settings:
      address:               smtp.gmail.co
      port:                  587
      user_name:             <%= ENV['GMAIL_USER'] %>
      password:              <%= ENV['GMAIL_PASS'] %>
      authentication:        :plain
      enable_starttls_auto:  true

  # mailer:
  #   delivery_method: :smtp
  #   settings:
  #     address:               email-smtp.us-east-1.amazonaws.com
  #     domain:                citroenrendezvous.org
  #     port:                  587
  #     user_name:             <%= ENV['RENDEZVOUS_SES_USER'] %>
  #     password:              <%= ENV['RENDEZVOUS_SES_PASSWORD'] %>
  #     authentication:        :login
  #     enable_starttls_auto:  true

  inquiry_recipients:
    - david.cossitt.levy@gmail.com
    - toaph@yahoo.com
    - tim@wordsareimages.com

test:
  facebook:
    app_id: <%= ENV['FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
  mailer:
    delivery_method: test
