# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22dcefc4102cccb447d5aa6938b79959ac9e7d7aa16de6e0a01c112f06c193aaa07d775ed853f16723fcc4d002e6454e1e7befa057c243e24980f0bff8f24ef2
  facebook:
    app_id: <%= ENV['FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>

test:
  secret_key_base: c88269933013e13009e0f28a1727a18fd7a8f21ea67f37c0fd15006e1b5ce38bd80859a4897089c119b1f95bfbb3eb5640f6bab2ecbc7f100c85b1daa7b66f0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: 22dcefc4102cccb447d5aa6938b79959ac9e7d7aa16de6e0a01c112f06c193aaa07d775ed853f16723fcc4d002e6454e1e7befa057c243e24980f0bff8f24ef2
  facebook:
    app_id: <%= ENV['RENDEZVOUS_FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['RENDEZVOUS_FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_SECRET'] %>

production:
  secret_key_base: 22dcefc4102cccb447d5aa6938b79959ac9e7d7aa16de6e0a01c112f06c193aaa07d775ed853f16723fcc4d002e6454e1e7befa057c243e24980f0bff8f24ef2
  facebook:
    app_id: <%= ENV['RENDEZVOUS_FACEBOOK_APP_ID'] %>
    app_secret: <%= ENV['RENDEZVOUS_FACEBOOK_APP_SECRET'] %>
  twitter:
    consumer_key: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['RENDEZVOUS_TWITTER_CONSUMER_SECRET'] %>
